#!/bin/bash

echo QCEIMS=${QCEIMS:=/storage/brno3-cerit/home/ljocha/work/QCEIMS_v.4.2}
echo HOURS=${HOURS:=24}
echo MEM=${MEM:=4gb}
echo SCRATCH=${SCRATCH:=8gb}

echo ORCA=${ORCA:=orca-4.2.1}


d=$(pwd)
bname=`basename $d`

DIR=$d/TMPQCEIMS
echo $DIR
if [ ! -d "$DIR" ]; then 
    echo "run mpspred first!"
    exit 
fi

#########################################
echo 'starting parallel qceims run on'

cd $DIR        

#########################################
# outer loop (runs until all is done)
#########################################

for vz in *
 do
   cd $vz 
   VZ_NUM=`echo $vz | awk -F . '{print $2}'`
   VZ_DIR=`pwd`
   cat > ${bname}_${VZ_NUM} <<EOF
#!/bin/bash

set -x
echo hostname: \`hostname\`
export OMP_NUM_THREADS=1

module add $ORCA

# Label for the run
#PBS -N qceims_${bname}_$VZ_NUM
#PBS -j oe

cd $VZ_DIR || { echo $VZ_DIR: \$!; exit 1 ; }
tdir=\$SCRATCHDIR
cp $VZ_DIR/* \$tdir
cd \$tdir

if [ ! -d "~/.XTBPARAM" ]; then
  cp -r $QCEIMS/.XTBPARAM ~
fi

$QCEIMS/qceims -prod > qceims.out 2>&1 
echo \$? >ready

cp * $VZ_DIR
cd $VZ_DIR
rm -rf \$tdir/*

EOF
#  this is the job (qceims calls dscf/grad, mopac or dftb+)
# VERY VERY IMPORTANT: termination of this job should produce
# a file <ready> in the subdir (e.g. by 'touch ready')
       # qsub -l select=1:ncpus=1:mem=4gb:scratch_local=8gb -q default@meta-pbs.metacentrum.cz ${bname}_${VZ_NUM}
        qsub -l walltime=$HOURS:0:0 -l select=1:ncpus=1:mem=$MEM:scratch_local=$SCRATCH ./${bname}_${VZ_NUM} >$VZ_DIR/jobid
        echo qsub -l walltime=$HOURS:0:0 -l select=1:ncpus=1:mem=$MEM:scratch_local=$SCRATCH ./${bname}_${VZ_NUM} \>$VZ_DIR/jobid
#
        echo "JOB  "${bname}_${VZ_NUM}"  STARTED"
   cd ..
 done
exit
