#!/bin/bash

d=`pwd`
bname=`basename $d`

DIR=`pwd`/TMPQCEIMS
if [ ! -d "$DIR" ]; then 
    echo "run mpspred first!"
    exit 
fi

#########################################
echo 'starting parallel qceims run on'

rm -f qceims.out
cd $DIR        

for vz in *
 do
   cd $vz 
   rm -f ready
#   rm -f *_*.[eo]*
   cd ..
   let TOTAL=TOTAL+1
   last=$vz
 done

echo TOTAL = $TOTAL directories

#########################################
# outer loop (runs until all is done)
#########################################

 for vz in *
 do
   cd $vz 
VZ_NUM=`echo $vz | awk -F . '{print $2}'`
VZ_DIR=`pwd`
cat > ${bname}_${VZ_NUM} <<EOF
#!/bin/bash

set -x
echo hostname: \`hostname\`
export OMP_NUM_THREADS=1

# Label for the run
#PBS -N qceims
#PBS -j oe

cd $VZ_DIR
mkdir /tmp1/\$USER
tdir=\$(mktemp -d /tmp1/\$USER/${vz}__XXXXXX)
cp $VZ_DIR/* \$tdir
cd \$tdir

qceims -prod > qceims.out 2>&1 
touch ready

cp * $VZ_DIR
cd $VZ_DIR
rm -rf \$tdir

if [ $vz = $last ]
then
     cd ..

     DONE=\`ls */ready | wc -l\`
     while [ \$DONE -ne $TOTAL ]
     do
       sleep 5
       DONE=\`ls */ready | wc -l\`
     done
       
     for dir in *
     do
       cat \$dir/qceims.res >> ../qceims.res
       cat \$dir/qceims.out >> ../qceims.out
     done
fi


EOF
#  this is the job (qceims calls dscf/grad, mopac or dftb+)
# VERY VERY IMPORTANT: termination of this job should produce
# a file <ready> in the subdir (e.g. by 'touch ready')
        qsub -q batch ${bname}_${VZ_NUM}
#
        echo "JOB  "${bname}_${VZ_NUM}"  STARTED"
   cd ..
 done
exit
